language: node_js
node_js:
- 8
env:
  global:
  - SAUCE_USERNAME=Exonum
  - secure: H6/KnkjbexZK1/jV/Z7zEUVI/CG7+0wi46uqgv4VP2RdJNkUN4oDVpUbzBHVW92Eb1JFw1FiQkRoKmvo2y4InuwmrRmc4hwSM5NNdPImmj6734nvkJf+p8c/kPTeYiz68MxqfRFef3tOZsQQM5tZjI2Qi4T+Z53MnFys8WFLkuvvUvKi9f/jj7Qkk2staoGIVIfiSRCkblrNrS27gIobz7lxuAcddS3lejLotE5CKB9V2W4YLqOGSXGBSMy4oStQqp2DllYun9/1Qq6ksrvfPFHHZoYL8dyI7IuiBC72VnF45D+gK83gAPGup9mDz7Q3QXWembXrBotHz+2tIgIijOjZ6cRVxmVM5x1QmSuZb+KdCjCUGZVNJlfLt5arNCBdiLYYdwgXtLHL65l00hmWUKBoV4WNxeI3/5yDruxEtnaKrwzgri44m6is+jvmfxEkM1Nb1gBw0+q+reKS84q+mobnUkLCHrD7+9Esxckr9a6FQBOce/Yvewvs30sS5iO9ynkEE9QpSsexF3D+exbUiHZCCFTCuoLwZGlCY/OGLT41C82C466b+tDkz9Q5hTMs8muOii74Xq7g/chTgSWuVDT/00BfUhaVQCZ/mx9u4xVC0cV3pkchq+LPbb+buWvuZsio9AFcE5h20Absv1LrNAjflec9x5WXreKtMHX9Q64=
cache:
  directories:
  - node_modules
script:
- npm run compile
- npm run test
- npm run test-saucelabs
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: exonum.bitfury@gmail.com
  api_key:
    secure: fvkH3N3pGbixckdhmT0jB0QCp+MzzwO2DAwEHiALbXKYlhR1Gq13aNvrvf8G1+n5gCy07wlOJqZd7eIMMiNt12bUPrLti23KRW6mbVWag2SXRwALXA7JOZ0f5vqmTgSewc3hnTTXLtXSzHwnCDXex3rcm/Xmm5LOTbZwFAeKuvLfsaLCODQ6eflJawGgwSXxbc8ZZUjEjc/F0IIbZZKtsFFX98vVDtbHjRnUENlH7tQ1SQhCe0Lowg46j2BI3yXpen76OATXNVMaEzoH3VGZbkkVnbw3fHTPatXnfqgRdfH58RAPzdTX1y1otojqzQURs3HOVVvw8y7Edj4p8x8wr3wCWvmkoDD4heaTMf7D4wem5/zrPFQV34QWYXBuoqm+xPhpZLlVwwoiCYopFRoWT4NqWpbYzh1N/f6vkPDv9Mjr9sL0XM+egsx4b2xpIK6qjl3aWelmDLow6rXZabIYQtcYjCEuMrFu/IglZI1fsuAyHiOB9W2WI3JRv0a8U8h7sOGGDmb6eUL4H0JgM8+q2pgDooTllkyt8aN3I0eKo2C9YP2TcxURhtPUarkad4PAsHyDn9oS3onqW/ZtBfZb/QwMtOn4G/xaO3ss5enjSG+oN1UUwO4JoCFm/mUKgumNlxYgtz9R/DF1C5K5rP5rXdwsQF/Vt3r1K3PRLhxdv3k=
  on:
    branch: master
    tags: true
    repo: exonum/exonum-client-anchoring
